### ISSUE TITLE
Remove dependency of react-scripts

### ISSUE THREAD

**Issue by trevormccasland** [trevormccasland/dotalytics#7] opened 2022-10-01 15:31 UTC
This project was initiated using create-react-app, this required us to use react-scripts. We should move away from react-scripts so we no longer have a dependency on create-react-app provided scripts.

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 15:37
Do we just need to change the package.json file? I am a beginner, sorry if this is a stupid question.

**Comment by trevormccasland** [comment] 2022-10-01 15:52
Yes I believe all that needs to be done is updating package.json and package-lock.json 
The end result should have the following working in package.json
```
"scripts": {
    "start": "webpack serve  --hot --open",
    "build": "webpack --config webpack.config.js --mode production"
  }
```
and the dependency of `"react-scripts": "5.0.1",` should be removed.

I'm not 100% sure on how to implement this, I believe the steps here are the way I wanted to initially setup this project https://dev.to/riddhiagrawal001/create-react-app-without-create-react-app-2lgd
so perhaps we can follow the steps to installing and configuring webpack, then switch to using that. It shouldn't be too difficult.

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 16:00
Can you assign it to me, I will give this a try, I just recently learnt react. I think its a interesting one. Thank you.

**Comment by trevormccasland** [comment] 2022-10-01 16:02
You are now assigned! Let me know if you have any questions with initial setup of the project or have any improvements to the README

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 16:03
Thanks, will start on it, in a few minutes.

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 16:51
Hey man, I followed the resource and built my own app and compared the package.json files. Ran all the commands on your file too. Two extra files babelrc and webpack config was added. And I was done with package.json file. but this error is showing regarding favicon. Any clue. 
![Screenshot from 2022-10-01 22-12-28](https://user-images.githubusercontent.com/110360901/193419561-0c6d0a91-69f3-46eb-a0d5-a889d36365fd.png)

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 16:53
This error was shown for npm start after following the resource article.

**Comment by trevormccasland** [comment] 2022-10-01 17:53
I think the PUBLIC_URL variable is something setup by react-scripts https://create-react-app.dev/docs/using-the-public-folder/

You can just update the href property in index.html to not include the variable like so:  `<link rel="icon" href="favicon.ico" />` and that should fix the error.

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 18:47
No, actually the problem is in webpack config. But I applied all the webpack commands. I think I am too new for this. You can unassign me. There maybe better people fit for this. Sorry for my incompetence.
![Screenshot from 2022-10-02 00-13-03](https://user-images.githubusercontent.com/110360901/193423735-b7f30f72-4d41-44d0-8669-b1a0fac8bf09.png)

**Comment by trevormccasland** [comment] 2022-10-01 19:04
If you create a pull request with your changes, I can take a look at it and see if I can finish it up for you.

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 19:27
Sure

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 20:05
Made the pr, do let me know if you figure it out. I would like learn from it.

**Comment by trevormccasland** [comment] 2022-10-01 20:34
I added a commit[1] to get webpack running. I'm not 100% sure I needed to install all the packages that I did in dev dependencies but I can slim it down in a separate change if I need to, thanks for your help with this!

[1] https://github.com/trevormccasland/dotalytics/pull/9/commits/313a3d2c0ae906f005c69027f4733e9162b35e5f

**Closed as completed** 2022-10-01 20:38 UTC
Labels: hacktoberfest

**Comment by ABHIGYAN-MOHANTA** [comment] 2022-10-01 22:47
Thank you!
